### ISSUE TITLE
Avoid compiling the whole project, after installing dotnetcore 3 preview 9

### ISSUE THREAD

**Issue by behnammby** [jsakamoto/Toolbelt.Blazor.HttpClientInterceptor#1]
Thank you for your useful package. 
After installing dotnet core 3 preview 9, the package avoids compiling the whole project and Removing the package resolves the issue. 
I think there might be some breaking changes in preview 9 targeting some components of the package.

**Comment by jsakamoto** [comment]
Unfortunately, I could not reproduce your problem.

At this time, "Toolbelt.Blazor.HttpClientInterceptor" looks work well on my sample site which is built on client-side Blazor WebAssembly framework.

Could you provide the project files to me as an attachment file of this issue?

**Comment by behnammby** [comment]
I'm sorry. Actually, this issue is for Toolbelt.Blazor.I18nText that V6.00 has solved. 
Thank you
