### ISSUE TITLE
GetCapturedContentAsync throws exception due to Expires == -1 

### ISSUE THREAD

**Issue by TH-Braemer** [jsakamoto/Toolbelt.Blazor.HttpClientInterceptor#12]
I have an API-middleware Exception handler that translates exceptions to a "500" response with the Exception details as a Json message.
When I try to read this content, I get an exception. The Exception is caused by the Expired Header on the content being "-1"

This is what I do:

```csharp
// This could potentially be an exception from the API
string? content = null;
try
{
    var capturedContent = await args.GetCapturedContentAsync();
    content = await capturedContent.ReadAsStringAsync();
}
catch {}
```

This fixes the issue for me:

```csharp
var httpContent = new ReadOnlyMemoryContent(this._CapturedContentBytes);
foreach (var contentHeader in this._CapturedContentHeaders)
{
    if (contentHeader.Key == "Expires")
    {
        continue;
    }
    httpContent.Headers.Add(contentHeader.Key, contentHeader.Value);
}
```

This is my API-Exception middleware:

```csharp
public class ExceptionHandler
{
    public static async Task GenerateExceptionResponseAsync(HttpContext context)
    {
        var exceptionHandlerPathFeature = context.Features.Get<IExceptionHandlerPathFeature>();
        var exception = exceptionHandlerPathFeature.Error;

        context.Response.ContentType = "application/json";

        context.Response.StatusCode = StatusCodes.Status500InternalServerError;
        await context.Response.WriteAsync(JsonSerializer.Serialize(new { status = StatusCodes.Status500InternalServerError, error = exception.Message }));
    }
}
```

I'm not setting the Expired header on the response, so I expect that it should be ignored if equal to "-1"?

PS: Sorry for the markup - I don't know wy It wont show correctly as code even though I use the codeblock tag

**Comment by jsakamoto** [comment]
@TH-Braemer Thank you for reporting!

I released the improved version v.10.2.0.

- https://www.nuget.org/packages/Toolbelt.Blazor.HttpClientInterceptor/10.2.0#release-body-tab

In that version, the `GetCapturedContentAsync()` method will proceed without throwing exceptions, even if the response has illegal content headers.

Would you try it out?

**Comment by TH-Braemer** [comment]
@jsakamoto Tested and it works perfectly 👍 
Thanks for the quick response.
