### ISSUE TITLE
AfterSendAsync fires twice with AddSingleton()

### ISSUE THREAD

**Issue by JPtenBerge** [jsakamoto/Toolbelt.Blazor.HttpClientInterceptor#5]
Ok, so this took me about an hour to figure out, but I'll keep it short.

In my project, I noticed my interceptor was being called twice. At first, I was thinking it had something to do with CORS, the browser sends an OPTIONS and a POST request, or maybe I registered it twice. But stripping and checking everything, I kept getting two calls to my `AfterSendAsync` event handler.

Recreating it in a separate project, everything went well. Finally I discovered the culprit.

	public static async Task Main(string[] args)
	{
		var builder = WebAssemblyHostBuilder.CreateDefault(args);
		builder.RootComponents.Add<App>("#app");

		builder.Services.AddHttpClientInterceptor();
		builder.Services.AddSingleton(sp => {
			return new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) }.EnableIntercept(sp);
		});

		var host = builder.Build();
		var interceptor = host.Services.GetService<HttpClientInterceptor>();

		interceptor.AfterSendAsync += ResolveJsonPaths;
		await host.RunAsync();
	}

	private async static Task ResolveJsonPaths(object sender, HttpClientInterceptorEventArgs e)
	{
		Console.WriteLine("In resolve " + e.Request.RequestUri.AbsoluteUri + " | " + e.Request.Method);
	}

It's the `AddSingleton()` for registering the `HttpClient`. If I change it to `AddScoped()`, everything works as expected. And even though [docs say that scoped services behave like singletons in Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/dependency-injection?view=aspnetcore-5.0#add-services-to-an-app) (See Service lifetime), apparently there are differences.

Now, I don't know if this has to do with your code or whether it's a Blazor WebAssembly thing, but I thought I'd report it.

And apart from all that, thanks for the library!

**Comment by jsakamoto** [comment]
Thank you for reporting!

This unexpected behavior comes from the development history of this library to keep compatibility with the lower version of this library.

And due to I missed concern about this scenario.

I'll try to resolve this issue.

**Comment by jsakamoto** [comment]
I published the new version v.9.2.1 that is fixed this issue.

- https://www.nuget.org/packages/Toolbelt.Blazor.HttpClientInterceptor/9.2.1

Could you try it?

**Comment by JPtenBerge** [comment]
> I published the new version v.9.2.1 that is fixed this issue.
> 
> * https://www.nuget.org/packages/Toolbelt.Blazor.HttpClientInterceptor/9.2.1
> 
> Could you try it?

Tried it, worked like a charm, just one lovely call. Nicely done sir, quick too!
